# Generated by Django 4.1 on 2022-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etfs", "0002_remove_etf_exchange_remove_etf_ticker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holdings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etf_id", models.PositiveBigIntegerField()),
                ("ticker", models.CharField(max_length=14)),
                ("percentage", models.FloatField()),
            ],
        ),
    ]
